import { useMemo, useState } from 'react';
import {
  CalendarDays,
  CheckCircle2,
  Database,
  Download,
  Eye,
  FileText,
  Files,
  Filter,
  RefreshCw,
  Route as RouteIcon,
  X,
} from 'lucide-react';
import { INITIAL_ROUTE_BASKET } from '../mock/routeBasketData';

type DownloadFormat = 'ALL' | 'PDF' | 'CSV' | 'JSON';
type ResourceId = 'report' | 'clean-etl' | 'route-basket';

interface CleanFareRecord {
  collection_date: string;
  travel_date: string;
  route_id: string;
  origin_city: string;
  destination_city: string;
  airline: string;
  cabin_class: string;
  lead_time_days: number;
  fare: number;
  currency: string;
  route_weight: number;
  weighted_fare: number;
  scrape_timestamp: string;
  source: string;
  etl_status: string;
}

interface RouteBasketDownloadRecord {
  route_id: string;
  origin_city: string;
  destination_city: string;
  weight: number;
  annual_passengers: number;
  status: string;
  last_updated: string;
}

interface DownloadResource {
  id: ResourceId;
  title: string;
  description: string;
  formats: Exclude<DownloadFormat, 'ALL'>[];
  defaultFormat: Exclude<DownloadFormat, 'ALL'>;
  icon: typeof FileText;
}

const AIRLINES = ['Akasa Air', 'Air India Express', 'SpiceJet'] as const;
const COLLECTION_DATES = ['2026-08-01', '2026-08-05', '2026-08-09', '2026-08-13', '2026-08-17', '2026-08-21', '2026-08-25', '2026-08-29'];
const LEAD_TIMES = [1, 7, 15, 30, 45];
const LAST_REFRESH = '29 Aug 2026 • 08:30 IST';
const APIX_VALUE = 85.1;
const PERIOD_CHANGE = -0.8;

const RESOURCES: DownloadResource[] = [
  {
    id: 'report',
    title: 'Monthly Airfare Price Index Report',
    description: 'Official monthly Airfare Price Index report generated by NSO for CPI analysis.',
    formats: ['PDF'],
    defaultFormat: 'PDF',
    icon: FileText,
  },
  {
    id: 'clean-etl',
    title: 'Clean Airfare Dataset (ETL Output)',
    description: 'Cleaned airfare observations after ETL preprocessing, used for APIx computation.',
    formats: ['CSV', 'JSON'],
    defaultFormat: 'CSV',
    icon: Database,
  },
  {
    id: 'route-basket',
    title: 'Route Basket & Weights Dataset',
    description: 'Official 24-route representative city-pair basket and CPI weights used in APIx computation.',
    formats: ['CSV', 'JSON'],
    defaultFormat: 'CSV',
    icon: RouteIcon,
  },
];

function addDays(dateValue: string, days: number) {
  const date = new Date(`${dateValue}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

function safeFilenamePart(value: string) {
  return value.replaceAll(/[^a-zA-Z0-9-]+/g, '_').replaceAll(/^_+|_+$/g, '');
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function csvFromRecords<T extends object>(records: T[]) {
  if (!records.length) return '';
  const keys = Object.keys(records[0]) as Array<keyof T>;
  const escape = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
  return [keys.join(','), ...records.map((record) => keys.map((key) => escape(record[key])).join(','))].join('\n');
}

function asciiPdfText(value: string) {
  return value
    .replaceAll('₹', 'Rs. ')
    .replaceAll('→', 'to')
    .replaceAll('–', '-')
    .replaceAll('\u2014', '-')
    .normalize('NFKD')
    .replaceAll(/[^\x20-\x7E]/g, '')
    .replaceAll('\\', '\\\\')
    .replaceAll('(', '\\(')
    .replaceAll(')', '\\)');
}

function createReportPdf(lines: Array<{ text: string; heading?: boolean }>) {
  const commands = [
    '0.09 0.41 0.67 rg',
    '0 710 612 82 re f',
    'BT /F1 21 Tf 1 1 1 rg 38 754 Td (VAYUSETU) Tj ET',
    'BT /F1 11 Tf 1 1 1 rg 38 732 Td (Government Airfare Price Index Portal) Tj ET',
  ];
  let y = 686;
  for (const line of lines.slice(0, 43)) {
    commands.push(`BT /F1 ${line.heading ? 11 : 8.7} Tf ${line.heading ? '0.09 0.41 0.67' : '0.15 0.20 0.29'} rg 38 ${y} Td (${asciiPdfText(line.text)}) Tj ET`);
    y -= line.heading ? 17 : 12;
  }
  commands.push('0.80 0.85 0.91 RG 38 42 m 574 42 l S');
  commands.push('BT /F1 8 Tf 0.40 0.47 0.58 rg 38 27 Td (Authorized government statistical output - VAYUSETU) Tj ET');
  const stream = commands.join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];
  const encoder = new TextEncoder();
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(encoder.encode(pdf).length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Blob([pdf], { type: 'application/pdf' });
}

function formatBadge(format: Exclude<DownloadFormat, 'ALL'>) {
  if (format === 'PDF') return 'border-red-200 bg-red-50 text-[#DC2626]';
  if (format === 'CSV') return 'border-green-200 bg-green-50 text-[#15803D]';
  return 'border-purple-200 bg-purple-50 text-[#7C3AED]';
}

export function DownloadsPage() {
  const [startDate, setStartDate] = useState('2026-08-01');
  const [endDate, setEndDate] = useState('2026-08-31');
  const [airline, setAirline] = useState('ALL');
  const [routeId, setRouteId] = useState('ALL');
  const [format, setFormat] = useState<DownloadFormat>('ALL');
  const [previewId, setPreviewId] = useState<ResourceId | null>(null);

  const routeBasket = useMemo<RouteBasketDownloadRecord[]>(() => {
    const normalized = INITIAL_ROUTE_BASKET.map((route) => ({
      route_id: route.route,
      origin_city: route.originCity,
      destination_city: route.destinationCity,
      weight: route.weight,
      annual_passengers: Math.round(route.weight / 100 * 76_000_000),
      status: 'Active',
      last_updated: '2026-08-29',
    }));
    if (normalized.length) {
      const difference = Number((100 - normalized.reduce((sum, route) => sum + route.weight, 0)).toFixed(2));
      normalized[0].weight = Number((normalized[0].weight + difference).toFixed(2));
    }
    return normalized;
  }, []);

  const allCleanRecords = useMemo<CleanFareRecord[]>(() => {
    const sourceCohorts = AIRLINES.map((name, index) => ({ airline: name, source: name, factor: 0.94 + index * 0.035 }));
    return routeBasket.flatMap((basketRoute, routeIndex) => {
      const anchorFare = 3600 + routeIndex * 145;
      return COLLECTION_DATES.flatMap((collectionDate, dateIndex) =>
        sourceCohorts.flatMap((cohort) =>
          LEAD_TIMES.map((leadTime) => {
            const leadFactor = leadTime === 1 ? 1.23 : leadTime === 7 ? 1.11 : leadTime === 15 ? 1.04 : leadTime === 30 ? 0.98 : 0.94;
            const fare = Math.round(anchorFare * cohort.factor * leadFactor * (0.985 + dateIndex * 0.006));
            return {
              collection_date: collectionDate,
              travel_date: addDays(collectionDate, leadTime),
              route_id: basketRoute.route_id,
              origin_city: basketRoute.origin_city,
              destination_city: basketRoute.destination_city,
              airline: cohort.airline,
              cabin_class: 'Economy',
              lead_time_days: leadTime,
              fare,
              currency: 'INR',
              route_weight: basketRoute.weight,
              weighted_fare: Number((fare * basketRoute.weight / 100).toFixed(2)),
              scrape_timestamp: `${collectionDate}T08:00:00Z`,
              source: cohort.source,
              etl_status: 'Processed',
            };
          }),
        ),
      );
    });
  }, [routeBasket]);

  const cleanRecords = useMemo(() => allCleanRecords.filter((record) =>
    record.collection_date >= startDate
    && record.collection_date <= endDate
    && (airline === 'ALL' || record.airline === airline)
    && (routeId === 'ALL' || record.route_id === routeId),
  ), [airline, allCleanRecords, endDate, routeId, startDate]);

  const filteredBasket = useMemo(() => routeBasket.filter((route) => routeId === 'ALL' || route.route_id === routeId), [routeBasket, routeId]);
  const visibleResources = RESOURCES.filter((resource) => format === 'ALL' || resource.formats.includes(format));

  const filenameSuffix = [
    airline !== 'ALL' ? safeFilenamePart(airline) : '',
    routeId !== 'ALL' ? safeFilenamePart(routeId) : '',
    startDate !== '2026-08-01' || endDate !== '2026-08-31' ? `${startDate}_to_${endDate}` : '',
  ].filter(Boolean).join('_');

  const reportLines = useMemo(() => {
    const sorted = routeBasket.map((route, index) => ({
      ...route,
      changePercent: Number((8.7 - index * 0.83 + (index % 3) * 1.2).toFixed(1)),
      currentFare: 4230 + index * 115,
    })).sort((a, b) => b.changePercent - a.changePercent);
    const airlineAverages = AIRLINES.map((name) => {
      const rows = cleanRecords.filter((record) => record.airline === name);
      const average = rows.length ? Math.round(rows.reduce((sum, record) => sum + record.fare, 0) / rows.length) : 0;
      return `${name}: Rs. ${average.toLocaleString('en-IN')} average fare (${rows.length} records)`;
    });
    const leadSummary = LEAD_TIMES.map((days) => {
      const rows = cleanRecords.filter((record) => record.lead_time_days === days);
      return `T+${days}: Rs. ${rows.length ? Math.round(rows.reduce((sum, record) => sum + record.fare, 0) / rows.length).toLocaleString('en-IN') : '0'}`;
    }).join(' | ');
    return [
      { text: 'MONTHLY AIRFARE PRICE INDEX REPORT - AUGUST 2026', heading: true },
      { text: `Reporting period: ${startDate} to ${endDate}` },
      { text: `Current APIx value: ${APIX_VALUE.toFixed(1)}` },
      { text: `Month-on-month change: ${PERIOD_CHANGE.toFixed(1)}%` },
      { text: 'Top 5 routes with highest fare increase', heading: true },
      ...sorted.slice(0, 5).map((route) => ({ text: `${route.route_id}: ${route.changePercent >= 0 ? '+' : ''}${route.changePercent.toFixed(1)}%` })),
      { text: 'Top 5 routes with highest fare decrease', heading: true },
      ...sorted.slice(-5).reverse().map((route) => ({ text: `${route.route_id}: ${route.changePercent >= 0 ? '+' : ''}${route.changePercent.toFixed(1)}%` })),
      { text: 'Airline-wise average fare summary', heading: true },
      ...airlineAverages.map((text) => ({ text })),
      { text: 'Route-wise inflation summary', heading: true },
      ...sorted.slice(0, 6).map((route) => ({ text: `${route.route_id}: fare Rs. ${route.currentFare.toLocaleString('en-IN')}; movement ${route.changePercent.toFixed(1)}%` })),
      { text: 'Lead-time elasticity summary', heading: true },
      { text: leadSummary },
      { text: 'Methodology', heading: true },
      { text: 'Matched airline/source cohort mean fares across a 24-route passenger-weighted basket.' },
      { text: 'Route weights are normalized over valid matched routes; movement is measured from the first valid calculated score.' },
    ];
  }, [cleanRecords, endDate, routeBasket, startDate]);

  const handleDownload = (resource: DownloadResource, requestedFormat: Exclude<DownloadFormat, 'ALL'> = resource.defaultFormat) => {
    const chosenFormat = requestedFormat;
    const suffix = filenameSuffix ? `_${filenameSuffix}` : '';
    if (resource.id === 'report') {
      downloadBlob('APIx_Report_August_2026.pdf', createReportPdf(reportLines));
      return;
    }
    const baseName = resource.id === 'clean-etl' ? 'Clean_Airfare_ETL_Dataset_August_2026' : 'Route_Basket_Weights_2026';
    const records = resource.id === 'clean-etl' ? cleanRecords : filteredBasket;
    if (chosenFormat === 'JSON') {
      downloadBlob(`${baseName}${suffix}.json`, new Blob([JSON.stringify(records, null, 2)], { type: 'application/json' }));
    } else {
      const csv = resource.id === 'clean-etl' ? csvFromRecords(cleanRecords) : csvFromRecords(filteredBasket);
      downloadBlob(`${baseName}${suffix}.csv`, new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    }
  };

  const previewResource = RESOURCES.find((resource) => resource.id === previewId) ?? null;
  const reportPreviewRows: Array<Record<string, unknown>> = [
    { field: 'Reporting Month', value: 'August 2026' },
    { field: 'APIx Value', value: APIX_VALUE },
    { field: 'Month-on-Month Change', value: `${PERIOD_CHANGE}%` },
    { field: 'Routes Covered', value: 24 },
    { field: 'Airlines Covered', value: 3 },
  ];
  const previewRecords: Array<Record<string, unknown>> = previewId === 'clean-etl'
    ? cleanRecords.slice(0, 5) as unknown as Array<Record<string, unknown>>
    : previewId === 'route-basket'
      ? filteredBasket.slice(0, 5) as unknown as Array<Record<string, unknown>>
      : reportPreviewRows;
  const previewCount = previewId === 'clean-etl' ? cleanRecords.length : previewId === 'route-basket' ? filteredBasket.length : 1;
  const previewColumns = Object.keys(previewRecords[0] ?? {});

  return (
    <div className="space-y-8 pb-16">
      <header className="border-b border-[#E2E8F0] pb-5">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#1769AA]"><Download className="h-4 w-4" /> Data distribution</div>
        <h1 className="mt-2 font-heading text-3xl font-extrabold tracking-tight text-[#172033] sm:text-4xl">Downloads Center</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-[#64748B]">Download authorized APIx reports, cleaned ETL observations and the official route basket used for airfare index computation.</p>
      </header>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[
          { label: 'Available Downloads', value: '3', detail: 'PDF, CSV and JSON outputs', icon: Files, tone: 'bg-blue-50 text-[#1769AA]' },
          { label: 'Latest APIx Report', value: 'August 2026', detail: 'Official APIx value: 85.1', icon: FileText, tone: 'bg-red-50 text-[#DC2626]' },
          { label: 'Last Dataset Refresh', value: '29 Aug 2026', detail: '08:30 IST • ETL processed', icon: RefreshCw, tone: 'bg-teal-50 text-[#0F8B8D]' },
          { label: 'Total Records Available', value: '2,880 Records', detail: 'Across 24 monitored routes and 3 airlines', icon: Database, tone: 'bg-purple-50 text-[#7C3AED]' },
        ].map((card) => (
          <div key={card.label} className="intel-card p-5">
            <div className={`mb-4 flex h-10 w-10 items-center justify-center rounded-xl ${card.tone}`}><card.icon className="h-5 w-5" /></div>
            <div className="text-[11px] font-bold uppercase tracking-wider text-[#94A3B8]">{card.label}</div>
            <div className="mt-1 font-heading text-2xl font-extrabold text-[#172033]">{card.value}</div>
            <div className="mt-1 text-xs text-[#64748B]">{card.detail}</div>
          </div>
        ))}
      </section>

      <section className="intel-card p-5">
        <div className="mb-4 flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-[#1769AA]"><Filter className="h-4 w-4" /> Download filters</div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          <label className="text-[11px] font-bold uppercase tracking-wide text-[#64748B]">From date<input type="date" value={startDate} max={endDate} onChange={(event) => setStartDate(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-medium text-[#172033]" /></label>
          <label className="text-[11px] font-bold uppercase tracking-wide text-[#64748B]">To date<input type="date" value={endDate} min={startDate} onChange={(event) => setEndDate(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-medium text-[#172033]" /></label>
          <label className="text-[11px] font-bold uppercase tracking-wide text-[#64748B]">Airline<select value={airline} onChange={(event) => setAirline(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-medium text-[#172033]"><option value="ALL">All 3 Airlines</option>{AIRLINES.map((name) => <option key={name}>{name}</option>)}</select></label>
          <label className="text-[11px] font-bold uppercase tracking-wide text-[#64748B]">Route<select value={routeId} onChange={(event) => setRouteId(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-medium text-[#172033]"><option value="ALL">All 24 Routes</option>{routeBasket.map((route) => <option key={route.route_id}>{route.route_id}</option>)}</select></label>
          <label className="text-[11px] font-bold uppercase tracking-wide text-[#64748B]">Format<select value={format} onChange={(event) => setFormat(event.target.value as DownloadFormat)} className="mt-1.5 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-medium text-[#172033]"><option value="ALL">All Formats</option><option>PDF</option><option>CSV</option><option>JSON</option></select></label>
        </div>
      </section>

      <section className="grid gap-5 lg:grid-cols-3">
        {visibleResources.map((resource) => {
          const Icon = resource.icon;
          const count = resource.id === 'clean-etl' ? cleanRecords.length : resource.id === 'route-basket' ? filteredBasket.length : 1;
          const metadata = resource.id === 'clean-etl'
            ? `${count.toLocaleString('en-IN')} records • 24 routes • 3 airlines • 1–31 Aug 2026`
            : resource.id === 'route-basket'
              ? `${count} routes • 100% total weight • ${count} active • Updated 29 Aug 2026`
              : 'August 2026 • APIx 85.1 • 24 routes • 3 airlines';
          return (
            <article key={resource.id} className="intel-card flex min-h-[330px] flex-col p-6">
              <div className="flex items-start justify-between gap-3">
                <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#1769AA]"><Icon className="h-6 w-6" /></div>
                <div className="flex gap-1.5">{resource.formats.map((item) => <span key={item} className={`rounded-lg border px-2 py-1 text-[10px] font-extrabold ${formatBadge(item)}`}>{item}</span>)}</div>
              </div>
              <h2 className="mt-5 font-heading text-lg font-extrabold text-[#172033]">{resource.title}</h2>
              <p className="mt-2 text-xs leading-5 text-[#64748B]">{resource.description}</p>
              <div className="mt-4 space-y-2 rounded-xl bg-[#F8FAFC] p-3 text-[11px] text-[#64748B]">
                <div className="flex justify-between gap-3"><span>Last updated</span><strong className="text-[#172033]">{LAST_REFRESH}</strong></div>
                <div className="flex justify-between gap-3"><span>Availability</span><strong className="text-[#15803D]">Ready</strong></div>
                <div className="border-t border-[#E2E8F0] pt-2 font-medium text-[#475569]">{metadata}</div>
              </div>
              <div className="mt-auto flex gap-2 pt-5">
                <button type="button" onClick={() => setPreviewId(resource.id)} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-[#CBD5E1] bg-white px-3 py-2.5 text-xs font-bold text-[#334155] hover:border-[#1769AA] hover:text-[#1769AA]"><Eye className="h-4 w-4" /> {resource.id === 'report' ? 'Preview PDF' : resource.id === 'clean-etl' ? 'Preview Dataset' : 'Preview Basket'}</button>
                {resource.formats.map((item) => (
                  <button key={item} type="button" onClick={() => handleDownload(resource, item)} className="flex flex-1 items-center justify-center gap-1.5 rounded-xl bg-[#1769AA] px-2.5 py-2.5 text-[11px] font-extrabold text-white shadow-sm hover:bg-[#12558A]"><Download className="h-3.5 w-3.5" /> {item}</button>
                ))}
              </div>
            </article>
          );
        })}
      </section>

      {!visibleResources.length && <div className="rounded-2xl border border-dashed border-[#CBD5E1] bg-white p-10 text-center text-sm text-[#64748B]">No resource supports the selected format.</div>}

      {previewResource && (
        <div className="fixed inset-0 z-[100] bg-[#0F172A]/45 backdrop-blur-sm" onMouseDown={() => setPreviewId(null)}>
          <aside className="absolute inset-y-0 right-0 w-full max-w-2xl overflow-y-auto border-l border-[#CBD5E1] bg-white shadow-2xl" onMouseDown={(event) => event.stopPropagation()}>
            <header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-[#E2E8F0] bg-white p-5 sm:p-6">
              <div><div className="text-xs font-bold uppercase tracking-wider text-[#1769AA]">Resource preview</div><h2 className="mt-1 font-heading text-xl font-extrabold text-[#172033]">{previewResource.title}</h2></div>
              <button type="button" onClick={() => setPreviewId(null)} className="rounded-xl border border-[#E2E8F0] p-2 text-[#64748B] hover:bg-[#F8FAFC]" aria-label="Close preview"><X className="h-5 w-5" /></button>
            </header>
            <div className="space-y-6 p-5 sm:p-6">
              <p className="text-sm leading-6 text-[#64748B]">{previewResource.description}</p>
              <div className="grid gap-3 sm:grid-cols-3">
                <div className="rounded-xl bg-[#F8FAFC] p-3"><CalendarDays className="h-4 w-4 text-[#1769AA]" /><div className="mt-2 text-[10px] font-bold uppercase text-[#94A3B8]">Last updated</div><div className="mt-1 text-xs font-bold text-[#172033]">{LAST_REFRESH}</div></div>
                <div className="rounded-xl bg-[#F8FAFC] p-3"><Database className="h-4 w-4 text-[#0F8B8D]" /><div className="mt-2 text-[10px] font-bold uppercase text-[#94A3B8]">Record count</div><div className="mt-1 text-xs font-bold text-[#172033]">{previewCount.toLocaleString('en-IN')}</div></div>
                <div className="rounded-xl bg-[#F8FAFC] p-3"><CheckCircle2 className="h-4 w-4 text-[#16A34A]" /><div className="mt-2 text-[10px] font-bold uppercase text-[#94A3B8]">File format</div><div className="mt-1 text-xs font-bold text-[#15803D]">{previewResource.formats.join(' / ')}</div></div>
              </div>
              <div>
                <h3 className="font-heading text-sm font-bold text-[#172033]">Schema preview</h3>
                <div className="mt-2 flex flex-wrap gap-1.5">{previewId === 'report' ? ['reporting_month', 'apix_value', 'period_change', 'route_movements', 'airline_summary', 'lead_time_summary', 'methodology'].map((key) => <span key={key} className="rounded-lg border border-blue-100 bg-blue-50 px-2 py-1 font-mono text-[10px] text-[#1769AA]">{key}</span>) : Object.keys((previewRecords[0] as object | undefined) ?? {}).map((key) => <span key={key} className="rounded-lg border border-blue-100 bg-blue-50 px-2 py-1 font-mono text-[10px] text-[#1769AA]">{key}</span>)}</div>
              </div>
              <div>
                <h3 className="font-heading text-sm font-bold text-[#172033]">Five sample records</h3>
                <div className="mt-2 max-h-[430px] overflow-auto rounded-2xl border border-[#E2E8F0]">
                  <table className="min-w-full whitespace-nowrap text-left text-[11px]">
                    <thead className="sticky top-0 bg-[#F1F5F9] text-[#475569]"><tr>{previewColumns.map((column) => <th key={column} className="border-b border-[#CBD5E1] px-3 py-2.5 font-extrabold">{column}</th>)}</tr></thead>
                    <tbody className="divide-y divide-[#E2E8F0] bg-white">{previewRecords.map((record, index) => <tr key={index} className="hover:bg-[#F8FAFC]">{previewColumns.map((column) => <td key={column} className="px-3 py-2.5 text-[#334155]">{String(record[column] ?? '')}</td>)}</tr>)}</tbody>
                  </table>
                </div>
              </div>
              <div className="flex gap-2">{previewResource.formats.map((item) => <button key={item} type="button" onClick={() => handleDownload(previewResource, item)} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#1769AA] px-4 py-3 text-xs font-extrabold text-white hover:bg-[#12558A]"><Download className="h-4 w-4" /> Download {item}</button>)}</div>
            </div>
          </aside>
        </div>
      )}
    </div>
  );
}
